### ISSUE TITLE
Chat tab floats off the baseline in IE8

### ISSUE THREAD

**Issue by ericras** [unl/VisitorChat#340]
Need something like: 

``` css
.ie8 #visitorChat_sound_container {
  height: 0;
}
```
